# Generated by Django 5.0.6 on 2024-06-18 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studyPlans", "0002_rename_date_task_deadlines"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="details",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
