# Generated by Django 5.0.6 on 2024-06-18 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("studyPlans", "0003_task_details"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="Label",
        ),
    ]
