# Generated by Django 5.0.6 on 2024-06-24 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("studyPlans", "0004_remove_task_label"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="user",
            new_name="user_id",
        ),
    ]
