# Generated by Django 5.0.6 on 2024-06-24 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("studyPlans", "0005_rename_user_task_user_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="user_id",
            new_name="user",
        ),
    ]
