# Generated by Django 5.0.6 on 2024-08-03 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studyPlans", "0006_rename_user_id_task_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="complexity",
            field=models.CharField(
                blank=True,
                choices=[("low", "Low"), ("normal", "Normal"), ("high", "High")],
                max_length=20,
            ),
        ),
    ]
