# Generated by Django 5.1 on 2024-10-07 07:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyPlans', '0007_alter_task_complexity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studyMethod', models.CharField(max_length=50)),
                ('stress_level', models.CharField(max_length=10, null=True)),
                ('noise_level', models.CharField(max_length=10, null=True)),
                ('environment', models.CharField(max_length=10, null=True)),
                ('session_date', models.DateTimeField(auto_now_add=True)),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='studyPlans.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
