# Generated by Django 5.1 on 2024-10-09 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyPlans', '0008_studysession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studysession',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studyPlans.task'),
        ),
    ]
