# Generated by Django 5.1 on 2024-10-12 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studyPlans', '0009_alter_studysession_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studysession',
            name='environment',
        ),
    ]
