# Generated by Django 5.0.6 on 2024-08-03 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moodTrack", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="moodtrack",
            name="context",
            field=models.CharField(
                blank=True,
                choices=[
                    ("wakeup", "Upon Waking"),
                    ("before_study", "Before Study"),
                    ("after_study", "After Study"),
                    ("end_day", "End of Day"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="moodtrack",
            name="custom_context",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
