# Generated by Django 5.0.6 on 2024-08-05 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moodTrack", "0002_moodtrack_context_moodtrack_custom_context"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="moodtrack",
            name="custom_context",
        ),
        migrations.AlterField(
            model_name="moodtrack",
            name="context",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
