# Generated by Django 5.0.6 on 2024-08-05 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moodTrack", "0003_remove_moodtrack_custom_context_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moodtrack",
            name="timestamp",
            field=models.DateTimeField(),
        ),
    ]
