# Generated by Django 5.0.6 on 2024-08-05 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moodTrack", "0004_alter_moodtrack_timestamp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moodtrack",
            name="timestamp",
            field=models.CharField(max_length=30),
        ),
    ]
