# Generated by Django 5.0.6 on 2024-05-15 08:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_remove_user_username_alter_user_first_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudyPrefernce",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "chronotype",
                    models.CharField(
                        choices=[
                            ("early_bird", "Early Bird"),
                            ("night_owl", "Night Owl"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "concentration",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("normal", "Normal"),
                            ("high", "High"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "studying_style",
                    models.CharField(
                        choices=[("group", "Group Study"), ("solo", "Solo Study")],
                        max_length=10,
                    ),
                ),
                ("procrastination", models.BooleanField()),
                ("physical_activity", models.TextField()),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
