# Generated by Django 5.1.1 on 2024-10-01 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charge_mqtt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='relayactivation',
            name='password',
            field=models.CharField(default=1, max_length=6),
            preserve_default=False,
        ),
    ]
