# Generated by Django 5.1.1 on 2024-10-09 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charge_mqtt', '0003_relayusage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relayusage',
            name='duration',
        ),
    ]
