# Generated by Django 5.0.6 on 2024-05-22 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RelayStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relay1_status', models.CharField(choices=[('START', 'Start'), ('STOP', 'Stop')], max_length=10)),
                ('relay2_status', models.CharField(choices=[('START', 'Start'), ('STOP', 'Stop')], max_length=10)),
            ],
        ),
    ]
